name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Ejercicio 01
      id: test-ejercicio-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Ejercicio 01
        setup-command: ''
        command: go test ./ejercicios/... -run ^TestSelectorActividades$
        timeout: 10
        max-score: 10
    - name: Test Ejercicio 02
      id: test-ejercicio-02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Ejercicio 02
        setup-command: ''
        command: go test ./ejercicios/... -run ^TestEjercicio2$
        timeout: 10
        max-score: 10
    - name: Test Ejercicio 03
      id: test-ejercicio-03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Ejercicio 03
        setup-command: ''
        command: go test ./ejercicios/... -run ^TestEjercicio3$
        timeout: 10
    - name: Test Ejercicio 04
      id: test-ejercicio-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Ejercicio 04
        setup-command: ''
        command: go test ./ejercicios/... -run ^TestFarolas$
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-EJERCICIO-01_RESULTS: "${{steps.test-ejercicio-01.outputs.result}}"
        TEST-EJERCICIO-02_RESULTS: "${{steps.test-ejercicio-02.outputs.result}}"
        TEST-EJERCICIO-03_RESULTS: "${{steps.test-ejercicio-03.outputs.result}}"
        TEST-EJERCICIO-04_RESULTS: "${{steps.test-ejercicio-04.outputs.result}}"
      with:
        runners: test-ejercicio-01,test-ejercicio-02,test-ejercicio-03,test-ejercicio-04
